# Generated by Django 2.2.2 on 2020-01-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.kwikot.com/?attachment_id=2889', max_length=500),
        ),
    ]
