# Generated by Django 2.2.2 on 2020-02-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.kwikot.com/wp-content/uploads/2017/10/Image-Coming-Soon-Placeholder.jpg', max_length=500),
        ),
    ]
